/** @type {import('next').NextConfig} */
const nextConfig = {
  allowedDevOrigins: ["192.168.1.129", "localhost", "127.0.0.1"],
  async redirects() {
    return [
      {
        source: "/login.txt",
        destination: "/login",
        permanent: false,
      },
      { source: "/membro", destination: "/member", permanent: false },
      { source: "/membro/blog", destination: "/member/articles", permanent: false },
      { source: "/membro/diretorio", destination: "/member/directory", permanent: false },
      { source: "/membro/medico/:id", destination: "/member/doctor/:id", permanent: false },
      { source: "/membro/chat", destination: "/member/chat", permanent: false },
      { source: "/membro/eventos", destination: "/member/events", permanent: false },
      { source: "/membro/eventos/meus-eventos", destination: "/member/events/my-events", permanent: false },
      { source: "/membro/webinars", destination: "/member/webinars", permanent: false },
      { source: "/membro/webinars/:id", destination: "/member/webinars/:id", permanent: false },
      { source: "/membro/minhas-postagens", destination: "/member/my-posts", permanent: false },
      { source: "/membro/postagens/:id", destination: "/member/posts/:id", permanent: false },
      { source: "/membro/criar", destination: "/member/create", permanent: false },
      { source: "/membro/editar/post/:id", destination: "/member/edit/post/:id", permanent: false },
      { source: "/membro/perfil", destination: "/member/profile", permanent: false },
      { source: "/admin/membros", destination: "/admin/members", permanent: false },
      { source: "/admin/postagens", destination: "/admin/posts", permanent: false },
      { source: "/admin/postagens/novo", destination: "/admin/posts/new", permanent: false },
      { source: "/admin/eventos", destination: "/admin/events", permanent: false },
      { source: "/admin/eventos/gerenciamento", destination: "/admin/events/management", permanent: false },
      { source: "/admin/configuracoes/email", destination: "/admin/settings/email", permanent: false },
      { source: "/admin/perfil", destination: "/admin/profile", permanent: false },
      { source: "/registro", destination: "/register", permanent: false },
      { source: "/politica-de-privacidade", destination: "/privacy-policy", permanent: false },
      { source: "/termos-de-uso", destination: "/terms-of-use", permanent: false },
    ]
  },
  async rewrites() {
    return [
      { source: "/member", destination: "/membro" },
      { source: "/member/articles", destination: "/membro/blog" },
      { source: "/member/directory", destination: "/membro/diretorio" },
      { source: "/member/doctor/:id", destination: "/membro/medico/:id" },
      { source: "/member/chat", destination: "/membro/chat" },
      { source: "/member/events", destination: "/membro/eventos" },
      { source: "/member/events/my-events", destination: "/membro/eventos/meus-eventos" },
      { source: "/member/webinars", destination: "/membro/webinars" },
      { source: "/member/webinars/:id", destination: "/membro/webinars/:id" },
      { source: "/member/my-posts", destination: "/membro/minhas-postagens" },
      { source: "/member/posts/:id", destination: "/membro/postagens/:id" },
      { source: "/member/create", destination: "/membro/criar" },
      { source: "/member/edit/post/:id", destination: "/membro/editar/post/:id" },
      { source: "/member/profile", destination: "/membro/perfil" },
      { source: "/admin/members", destination: "/admin/membros" },
      { source: "/admin/posts", destination: "/admin/postagens" },
      { source: "/admin/posts/new", destination: "/admin/postagens/novo" },
      { source: "/admin/events", destination: "/admin/eventos" },
      { source: "/admin/events/management", destination: "/admin/eventos/gerenciamento" },
      { source: "/admin/settings/email", destination: "/admin/configuracoes/email" },
      { source: "/admin/profile", destination: "/admin/perfil" },
      { source: "/register", destination: "/registro" },
      { source: "/privacy-policy", destination: "/politica-de-privacidade" },
      { source: "/terms-of-use", destination: "/termos-de-uso" },
    ]
  },
}

module.exports = nextConfig
